auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /loki-wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki-data/index
    cache_location: /loki-data/cache
    shared_store: filesystem
  filesystem:
    directory: /loki-data/chunks

compactor:
  working_directory: /loki-data/compactor
  shared_store: filesystem

limits_config:
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_concurrent_tail_requests: 20
