server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # App logs
  - job_name: demo-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: demo-app
          __path__: /app/logs/*.log   # Promtail reads all log files in /app/logs

    pipeline_stages:
      - json:
          expressions:
            method: method
            route: route
            status_code: status
            duration_s: duration_s
      - labels:
          method:
          route:
          status_code:

  # Docker container logs (optional)
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            log: log
      - labels:
          log:
