global:
  scrape_interval: 3s
  evaluation_interval: 3s


rule_files:
- /etc/prometheus/rules.yml


scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']


- job_name: 'demo-app'
  metrics_path: /metrics
  static_configs:
  - targets: ['app:3000']


- job_name: 'loki'
  metrics_path: /metrics
  static_configs:
  - targets: ['loki:3100']


- job_name: 'jaeger'
  metrics_path: /metrics
  static_configs:
  - targets: ['jaeger:16686']