groups:
  - name: demo-recording-rules
    interval: 3s  # recording rule evaluation interval

    rules:
      # 1. Request rate per route (RPS)
      - record: job:app_http_requests_per_second
        expr: sum by (route) (rate(app_http_requests_total[15s]))

      # 2. p95 latency per route
      - record: job:app_http_request_duration_seconds_p95
        expr: |
          histogram_quantile(
            0.95,
            sum by (le, route) (
              rate(app_http_request_duration_seconds_bucket[15s])
            )
          )

      # 3. Error rate percentage per route
      - record: job:app_http_error_rate
        expr: |
          100 *
          sum by (route) (rate(app_http_requests_total{status_code=~"5.."}[15s]))
          /
          sum by (route) (rate(app_http_requests_total[15s]))

      # 4. Success rate percentage per route
      - record: job:app_http_success_rate
        expr: |
          100 *
          sum by (route) (rate(app_http_requests_total{status_code!~"5.."}[15s]))
          /
          sum by (route) (rate(app_http_requests_total[15s]))
